title: Coastal Marsh Acoustic Monitoring Analysis
theme: jekyll-theme-cayman
description: |
  Research landing page for tracking acoustic monitoring efforts
  in coastal marshes along the Delaware and Barnegat Bays.
author: Kelly Faller
