title: Coastal Marsh Acoustic Monitoring
description: Research landing page for tracking acoustic monitoring efforts in coastal marshes along the Delaware and Barnegat Bays.
url: "https://kellyfaller.github.io" # your GitHub username site
baseurl: "/Coastal-Marsh-Acoustic-Monitoring-Analysis" # repo name for project site

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Author settings
author:
  name: "Kelly Faller"
  avatar: "/Coastal-Marsh-Acoustic-Monitoring-Analysis/assets/css/img/author.jpg" 
  bio: "Graduate Student, Rutgers University"
  location: "NJ, USA"
  email: "kellynfaller@gmail.com"
  links:
    - label: "Personal Website"
      icon: "/assets/css/img/Project_logo.jpg" 
      url: "kellynfaller.wixsite.com/aboutme"
    - label: "LinkedIn" 
      icon: "/assets/css/img/linkedin.jpg"
      url: "https://www.linkedin.com/in/kellynfaller/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kellyfaller"
  
# Author Profile
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

# Google Analytics, Disqus (optional)
google_analytics: ""
comments: false
