title: Coastal Marsh Acoustic Monitoring Analysis
theme: minimal-mistakes-jekyll
description: |
  Research landing page for tracking acoustic monitoring efforts
  in coastal marshes along the Delaware and Barnegat Bays.
author: Kelly Faller
sass:
  sass_dir: _sass
